name: Cakes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59603
title: Cakes By Ashley Perry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#ffffff'
    - '#6d6e72'
    - '#ed2027'
    - '#ffd602'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.6700432654470205
  rhythmicContrast: 0.75
purpose: []
