title: Cakes By Ashley Perry
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9856631
  brandStrength: 0.9551972
  lightness: 1
  brandColors:
    - '#FEFFFD'
    - '#5B4120'
    - '#1E100D'
    - '#C7C9DF'
    - '#3E83C4'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Cakes
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.59603
layout_spectrum: 0.6577061
