name: Cakes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59603
title: Cakes By Ashley Perry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#846496'
    - '#b8b8b8'
    - '#44192d'
    - '#5e661a'
  brandStrength: 0.6875
  lightness: 0.7584928898140788
  saturation: 0.6700432654470205
  rhythmicContrast: 0.8258843151852489
purpose: []
